### ISSUE TITLE
Plugin removing valid -moz- prefix for ::selection

### ISSUE THREAD

**Issue by AllThingsSmitty** [mikaeljorhult/brackets-autoprefixer#36]
Referencing [this issue](https://github.com/postcss/autoprefixer/issues/417). There seems to be an issue with the Brackets plugin.

Current input:
```css
::-moz-selection {
  background: #b3d4fc;
}
::selection {
  background: #b3d4fc;
}
```
Current output:
```css
::selection {
  background: #b3d4fc;
}
```

According to [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#compat_hint1) for ::selection the -moz- prefix is required.

I raised this as [an issue](https://github.com/postcss/autoprefixer/issues/417) with Autoprefixer, but their tests show the `-moz-` prefix isn't removed. The Brackets plugin is removing it.
